name = "r2-proxy-worker"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "4ca1b102baca2e7067daf57e186e20c4"

# R2 bucket binding
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "librocco-ci"
remote = true

# Routes - bind to test.libroc.co using zone route
[[routes]]
pattern = "test.libroc.co/*"
zone_name = "libroc.co"
